export enum DjsAdapterErrorCodes {
    MIXED_LISTENER_TYPE = 'MIXED_LISTENER_TYPE',
    ADAPTER_ALREADY_INITIALIZED = 'ADAPTER_ALREADY_INITIALIZED',
    ADAPTER_NOT_INITIALIZED = 'ADAPTER_NOT_INITIALIZED',
    INVALID_HANDLER_METADATA = 'INVALID_HANDLER_METADATA',
    INTERNAL_ADAPTER_ERROR = 'INTERNAL_ADAPTER_ERROR',
}
