import { importAllFilesFrom } from '@nodecord/common';
import { unlinkSync } from 'fs';

/**
 * Clean all .js files generated by the TypeScript compiler.
 */
(async () => {
    const files = await importAllFilesFrom('./src/scripts/clean.ts');
    for (const file of files) {
        if (!file.name.endsWith('.js')) continue;

        console.log(`Removing ${file.name}`);
        unlinkSync(file.path);
    }
})();
